# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
#   default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   port: 5433
#   timeout: 5000
#   host: localhost
#   username: postgres
#   password: postgres

# development:
#   <<: *default
#   database:  activeadmin_dev

# test:
#   <<: *default
#   database: activeadmin_test

# production:
#   <<: *default
#   database: activeadmin_production
development:
  adapter: postgresql
  encoding: unicode
  database: activeadmin_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: activeadmin_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: activeadmin_production
  pool: 5
  username: postgres
  password: postgres